# Generated by Django 3.2 on 2021-04-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='picrure',
            field=models.CharField(default='1.png', max_length=10),
            preserve_default=False,
        ),
    ]
