# Generated by Django 3.2 on 2021-04-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_food_picrure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='picrure',
            new_name='picture',
        ),
    ]
