# Generated by Django 3.2 on 2021-04-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_picrure_food_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='picture',
            field=models.CharField(default='img/objects/1.png', max_length=10),
            preserve_default=False,
        ),
    ]
